SERVER_LISTEN_HOST: 0.0.0.0
SERVER_PORT: 8080
SERVER_HOST: http://silent-assassin.<namespace>.svc.cluster.local
LABEL_SELECTORS: cloud.google.com/gke-preemptible=true

SPOTTER:
  POLL_INTERVAL_MS: 60000
  WHITE_LIST_INTERVAL_HOURS: 19:30-00:30  #IST 12:00-14:00 IST 00:00-06:00

KILLER:
  POLL_INTERVAL_MS: 60000
  DRAINING_TIMEOUT_WHEN_NODE_EXPIRED_MS: 300000
  DRAINING_TIMEOUT_WHEN_NODE_PREEMPTED_MS: 30000
SHIFTER:
  POLL_INTERVAL_MS: 900000 # This should be greater that 15 mins.
  WHITE_LIST_INTERVAL_HOURS: 06:30-16:00
  NP_RESIZE_TIMEOUT_MINS: 10
  SLEEP_AFTER_NODE_DELETION_MS: 120000

LOGGER:
  LEVEL: debug # debug | info | warn | error

KUBERNETES:
  RUN_MODE: OutCluster # InCluster | OutCluster

SLACK:
  WEBHOOK_URL: <slack-url>
  USERNAME: SILENT ASSASSIN
  CHANNEL: silent-assassin-alerts
  SLACK_ICON_URL: <slack-icon-url>

CLIENT:
  SERVER_RETRIES: 4
  WATCH_MAINTAINANCE_EVENTS: true